#!/usr/bin/env python3
"""
Database migration script to upgrade from ImageMetadata to FileMetadata
Run this after updating the models to migrate existing data.
"""

import os
import sys
from datetime import datetime

# Add the app directory to the path
sys.path.insert(0, os.path.dirname(__file__))

from app import create_app
from app.models import db, ImageMetadata, FileMetadata

def migrate_metadata():
    """Migrate data from ImageMetadata to FileMetadata"""
    app = create_app()

    with app.app_context():
        print("🔄 Starting database migration...")

        # Check if ImageMetadata table exists and has data
        try:
            old_metadata_count = ImageMetadata.query.count()
            print(f"📊 Found {old_metadata_count} records in ImageMetadata table")

            if old_metadata_count == 0:
                print("✅ No data to migrate")
                return

            # Migrate data
            migrated_count = 0
            for old_meta in ImageMetadata.query.all():
                # Check if already migrated
                existing = FileMetadata.query.filter_by(
                    folder_path=old_meta.folder_path,
                    filename=old_meta.filename
                ).first()

                if existing:
                    print(f"⏭️  Skipping {old_meta.filename} (already migrated)")
                    continue

                # Determine file type (assume image if not video)
                file_path = os.path.join(
                    os.getenv('DATASET_PATH', os.path.join(os.path.dirname(__file__), 'dataset')),
                    old_meta.folder_path,
                    old_meta.filename
                )

                from pathlib import Path
                file_ext = Path(old_meta.filename).suffix.lower()
                if file_ext in ['.mp4', '.mov', '.avi', '.webm']:
                    file_type = 'video'
                elif file_ext == '.gif':
                    file_type = 'gif'
                else:
                    file_type = 'image'

                # Get file size
                try:
                    file_size = os.path.getsize(file_path)
                except:
                    file_size = old_meta.file_size

                # Create new metadata record
                new_meta = FileMetadata(
                    folder_path=old_meta.folder_path,
                    filename=old_meta.filename,
                    file_type=file_type,
                    file_size=file_size,
                    width=old_meta.width,
                    height=old_meta.height,
                    thumbnail_path=None,  # Will be generated by background scanner
                    created_at=old_meta.created_at,
                    modified_at=datetime.utcnow()
                )

                db.session.add(new_meta)
                migrated_count += 1

                # Commit in batches
                if migrated_count % 100 == 0:
                    db.session.commit()
                    print(f"📝 Migrated {migrated_count}/{old_metadata_count} records")

            # Final commit
            db.session.commit()
            print(f"✅ Migration complete! Migrated {migrated_count} records")

            # Optional: Drop old table
            print("🗑️  Keeping old ImageMetadata table for safety")
            print("   You can manually drop it later if everything works")

        except Exception as e:
            print(f"❌ Migration failed: {e}")
            db.session.rollback()
            return False

    return True

if __name__ == "__main__":
    success = migrate_metadata()
    if success:
        print("\n🎉 Migration successful!")
        print("Next steps:")
        print("1. Run the background scanner: python -c 'from app.utils import scan_folder_background; scan_folder_background(\"dataset\", \"\")'")
        print("2. Start the server: python run.py")
    else:
        print("\n❌ Migration failed!")
        sys.exit(1)