#!/usr/bin/env python3
"""
Scan thumbnails generated by fast_thumbs.sh into the database.
Run this AFTER running fast_thumbs.sh
"""

import os
import sys
import argparse
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from app import create_app, db
from app.models import FileMetadata

IMAGE_EXTENSIONS = {'.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.tiff', '.tif'}
VIDEO_EXTENSIONS = {'.mp4', '.avi', '.mov', '.mkv', '.webm', '.m4v', '.wmv', '.flv'}


def get_file_type(filepath):
    ext = os.path.splitext(filepath)[1].lower()
    if ext in IMAGE_EXTENSIONS:
        return 'image'
    elif ext in VIDEO_EXTENSIONS:
        return 'video'
    return 'unknown'


def find_thumbnail(thumb_dir, folder_path, filename):
    """Find thumbnail for a file (could be .jpg or .webp)"""
    name_no_ext = os.path.splitext(filename)[0]
    thumb_folder = os.path.join(thumb_dir, folder_path)
    
    # Check for .jpg thumbnail
    jpg_thumb = os.path.join(thumb_folder, f"{name_no_ext}.jpg")
    if os.path.exists(jpg_thumb):
        return jpg_thumb
    
    # Check for .webp thumbnail (for GIFs)
    webp_thumb = os.path.join(thumb_folder, f"{name_no_ext}.webp")
    if os.path.exists(webp_thumb):
        return webp_thumb
    
    return None


def main():
    parser = argparse.ArgumentParser(description='Scan files and thumbnails into database')
    parser.add_argument('--source', '-s', required=True, help='Source dataset directory')
    parser.add_argument('--thumbs', '-t', required=True, help='Thumbnails directory')
    parser.add_argument('--force', '-f', action='store_true', help='Update existing records')
    parser.add_argument('--dry-run', action='store_true', help='Show what would be done')
    
    args = parser.parse_args()
    
    source_dir = os.path.abspath(args.source)
    thumb_dir = os.path.abspath(args.thumbs)
    
    if not os.path.exists(source_dir):
        print(f"❌ Source directory not found: {source_dir}")
        sys.exit(1)
    
    if not os.path.exists(thumb_dir):
        print(f"❌ Thumbnails directory not found: {thumb_dir}")
        sys.exit(1)
    
    print("=" * 60)
    print("📂 Scanning files into database")
    print("=" * 60)
    print(f"Source: {source_dir}")
    print(f"Thumbs: {thumb_dir}")
    print(f"Force:  {args.force}")
    print("=" * 60)
    
    # Find all media files
    print("\nScanning for files...")
    all_files = []
    supported = IMAGE_EXTENSIONS | VIDEO_EXTENSIONS
    
    for root, dirs, files in os.walk(source_dir):
        # Skip thumbnail directories
        dirs[:] = [d for d in dirs if d not in ('thumbnails', 'thumbs', '.thumbs')]
        
        for filename in files:
            ext = os.path.splitext(filename)[1].lower()
            if ext in supported:
                filepath = os.path.join(root, filename)
                rel_path = os.path.relpath(filepath, source_dir)
                all_files.append((filepath, rel_path))
    
    print(f"Found {len(all_files)} media files")
    
    if args.dry_run:
        print("\n[DRY RUN] Would process:")
        for _, rel_path in all_files[:20]:
            print(f"  - {rel_path}")
        if len(all_files) > 20:
            print(f"  ... and {len(all_files) - 20} more")
        return
    
    # Create Flask app context
    app = create_app()
    
    # Get existing records
    print("Checking existing records...")
    with app.app_context():
        existing = {}
        for fm in FileMetadata.query.all():
            existing[(fm.folder_path, fm.filename)] = fm
        print(f"Found {len(existing)} existing records")
    
    # Process files
    print(f"\nProcessing {len(all_files)} files...")
    
    added = 0
    updated = 0
    skipped = 0
    with_thumb = 0
    errors = 0
    
    with app.app_context():
        for i, (filepath, rel_path) in enumerate(all_files, 1):
            try:
                folder_path = os.path.dirname(rel_path)
                filename = os.path.basename(rel_path)
                
                # Find thumbnail
                thumb_path = find_thumbnail(thumb_dir, folder_path, filename)
                if thumb_path:
                    with_thumb += 1
                
                key = (folder_path, filename)
                
                if key in existing:
                    if args.force:
                        # Update existing
                        fm = existing[key]
                        fm.thumbnail_path = thumb_path
                        fm.file_size = os.path.getsize(filepath)
                        fm.modified_at = datetime.utcnow()
                        updated += 1
                    else:
                        skipped += 1
                        continue
                else:
                    # Create new record
                    fm = FileMetadata(
                        folder_path=folder_path,
                        filename=filename,
                        file_type=get_file_type(filepath),
                        file_size=os.path.getsize(filepath),
                        thumbnail_path=thumb_path
                    )
                    db.session.add(fm)
                    added += 1
                
                # Commit in batches
                if i % 1000 == 0:
                    db.session.commit()
                    print(f"[{i}/{len(all_files)}] Added: {added}, Updated: {updated}, Skipped: {skipped}")
            
            except Exception as e:
                errors += 1
                print(f"Error processing {rel_path}: {e}")
        
        # Final commit
        db.session.commit()
    
    print("\n" + "=" * 60)
    print("✅ Done!")
    print(f"   Added:       {added}")
    print(f"   Updated:     {updated}")
    print(f"   Skipped:     {skipped}")
    print(f"   With thumbs: {with_thumb}")
    print(f"   Errors:      {errors}")
    print("=" * 60)


if __name__ == '__main__':
    main()
